<a href="https://colab.research.google.com/github/jerry3831/L.O.S-PRED/blob/main/L_O_S_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/New folder/Mortality_incidence_sociodemographic_and_clinical_data_in_COVID19_patients.xlsx")
data.to_csv('patients.csv')

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/New folder/cw_22_23_24.csv')

In [ ]:
df.head()

,adm_type,shift_from,ssc,yr_nae,m_no,mrn,pt_name,sex,disease,D.O.A,D.O.D,status,consultant,L.O.S
0,Shift From,ER,No,1,1,21845698,Hara Bibi,F,STEMI,1-Jan-22,1-Jan-22,Discharge,Imran Khan,0
1,Shift From,ER,No,2,2,22000071,Taj Rehman,M,ADHF,1-Jan-22,5-Jan-22,Discharge,Malik Faisal,4
2,Shift From,ER,No,3,3,21838760,Bakhtawar Shah,M,ihd,1-Jan-22,10-Jan-22,Discharge,Asif Iqbal,9
3,Shift From,ER,No,4,4,22000251,Arasal Jan Bibi,F,NaN,1-Jan-22,7-Jan-22,Discharge,Sher Bahadar,6
4,Shift From,Neu,No,5,5,21825110,Khad Mewa,F,NaN,1-Jan-22,2-Jan-22,Discharge,Tariq Nawaz,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9573 entries, 0 to 9572
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   adm_type    9573 non-null   object
 1   shift_from  9573 non-null   object
 2   ssc         9573 non-null   object
 3   yr_nae      9573 non-null   int64
 4   m_no        9573 non-null   int64
 5   mrn         9573 non-null   object
 6   pt_name     9573 non-null   object
 7   sex         9573 non-null   object
 8   disease     7481 non-null   object
 9   D.O.A       9573 non-null   object
 10  D.O.D       9573 non-null   object
 11  status      9573 non-null   object
 12  consultant  9573 non-null   object
 13  L.O.S       9573 non-null   int64
dtypes: int64(3), object(11)
memory usage: 1.0+ MB